// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  errMsg: string;
  input: string;
  label: string;
  segments: string;
  segments_item: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
