// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  dot_svg: string;
  dot_svg_cross: string;
  dot_svg_thumb: string;
  dot_wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
