// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  SVG_container: string;
  SVG_controlPath: string;
  SVG_dotsContainer: string;
  SVG_path: string;
  SVG_wrapper: string;
  app: string;
  view: string;
}
export const cssExports: CssExports;
export default cssExports;
