// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  SVG_container: string;
  SVG_controlItem: string;
  SVG_controls: string;
  SVG_wrapper: string;
  app: string;
}
export const cssExports: CssExports;
export default cssExports;
