// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  button: string;
  button_active: string;
  closeButton: string;
  header: string;
  settings: string;
  settingsIcon: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
