// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  control: string;
  label: string;
  msg: string;
  toggler: string;
  toggler_active: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
